---
name: Setup Cloudflare WARP
description: Setup Cloudflare WARP for secure network access on GitHub MacOS runners

outputs:
  certificate_path:
    description: Path to the Cloudflare inspection certificate
    value: ${{ steps.install_cert.outputs.certificate_path }}

runs:
  using: composite
  steps:
    - name: Get secrets from Vault
      id: secrets
      uses: SonarSource/vault-action-wrapper@320bd31b03e5dacaac6be51bbbb15adf7caccc32 # 3.1.0
      with:
        secrets: |
          development/kv/data/cloudflare/warp-github-runner client-id | CLOUDFLARE_AUTH_CLIENT_ID;
          development/kv/data/cloudflare/warp-github-runner client-secret | CLOUDFLARE_AUTH_CLIENT_SECRET;
          development/kv/data/cloudflare/warp-github-runner device-posture-secret | CLOUDFLARE_DEVICE_SECRET;
          development/kv/data/cloudflare/warp-github-runner inspection-certificate | CLOUDFLARE_INSPECTION_CERTIFICATE;

    - name: Setup prerequisites
      id: install_cert
      shell: bash
      env:
        CLOUDFLARE_DEVICE_SECRET: ${{ fromJSON(steps.secrets.outputs.vault).CLOUDFLARE_DEVICE_SECRET }}
        CLOUDFLARE_INSPECTION_CERTIFICATE: ${{ fromJSON(steps.secrets.outputs.vault).CLOUDFLARE_INSPECTION_CERTIFICATE }}
      run: |
        bash "${{ github.action_path }}/scripts/setup-prerequisites.sh"

    - name: Setup Cloudflare WARP
      id: setup_warp
      shell: bash
      run: |
        bash "${{ github.action_path }}/scripts/setup-warp.sh" \
          --version beta \
          --organization sonarsource \
          --auth-client-id "${{ fromJSON(steps.secrets.outputs.vault).CLOUDFLARE_AUTH_CLIENT_ID }}" \
          --auth-client-secret "${{ fromJSON(steps.secrets.outputs.vault).CLOUDFLARE_AUTH_CLIENT_SECRET }}"

    - name: Wait for WARP connection to be ready
      shell: bash
      continue-on-error: true
      run: |
        echo "::group::Waiting for WARP connection"
        if bash "${{ github.action_path }}/wait-for-warp-connection.sh"; then
          echo "::endgroup::"
          echo "✅ WARP connection established successfully"
        else
          echo "::endgroup::"
          echo "::warning::⚠️ WARP connection failed - job will continue without WARP connectivity"
          exit 1
        fi
